on: [push, pull_request]

jobs:
  builds:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Windows VS 16 - Conan 1.x", os: "windows-2019", generator: "Visual Studio 16 2019", conan_version: "1.*" }
          - { name: "Windows VS 17 - Conan 2.x", os: "windows-2022", generator: "Visual Studio 17 2022", conan_version: "2.*" }
    name: ${{ matrix.config.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        if: matrix.config.name == 'Windows'
      - name: Install Conan
        run: |
          pip install conan==${{ matrix.config.conan_version }} cmake
          conan user
          conan --version
          cmake --version
      - name: Install dependencies via Conan
        # TODO: Fix cpack
        run: |
          conan config set general.revisions_enabled=True
          conan remote add bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/public-conan
          echo "Conan install"
          conan install . --build missing
      - name: CMake
        # TODO: Fix cpack
        run: |
          echo "CMake configuration"
          cmake --preset default
          echo "CMake build"
          cmake --build --preset release
          echo "CMake install"
          cmake --install .
      - name: Create package
        # TODO: Fix cpack
        run: |        
          echo "Create package"
          echo "::set-env name=ARTIFACT_FILE::$(ls sauerbraten*.zip)"
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        # 
        with:
          name: ${{ env.ARTIFACT_FILE }}
          path: |
            bin/
            bin_unix
            bin64/
            data/
            src/
            sauerbraten.bat
            sauerbraten_unix
            server-init.cfg
            server.bat
            CMakeLists.txt
            conanfile.txt
            .gitignore
